CREATE TABLE DASHBOARD_FINANCEIRO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    GASTO_FIXO NUMBER(10,2),
    GASTO_MENSAL NUMBER(10,2),
    FATURAMENTO_DESEJADO NUMBER(10,2),
    LUCRO_ESTIMADO NUMBER(10,2)
);

INSERT INTO DASHBOARD_FINANCEIRO (
    GASTO_FIXO,
    GASTO_MENSAL,
    FATURAMENTO_DESEJADO,
    LUCRO_ESTIMADO
)
VALUES (
    310,
    170,
    4740,
    4260
);